In [1]:
import pandas as pd


# Replace with the filepath to your csv file
file_path = "C:/Users/arjyo/simulation/unnamed/openstudio/run/epluszsz.csv"

# Read the Excel file into a DataFrame
df = pd.read_csv(file_path)


In [2]:
# Identify columns with all observations as 0
columns_to_remove = df.columns[df.all() == 0]



In [3]:
# Drop columns with all observations as 0
df = df.drop(columns=columns_to_remove)

In [4]:
df.drop(df.columns[[2, 3,4,5,6]], axis=1, inplace=True)

In [5]:
new_column_name = 'cool_load'

# Rename the first column
df.rename(columns={df.columns[1]: new_column_name}, inplace=True)

In [6]:
df.head()

Time  cool_load
0  00:10:00   58773.36
1  00:20:00   58726.31
2  00:30:00   58680.09
3  00:40:00   58634.68
4  00:50:00   58590.05

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense


C:\Users\arjyo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [18]:
# Normalize the 'cool_load' values
scaler = MinMaxScaler(feature_range=(0, 1))
df['cool_load_normalized'] = scaler.fit_transform(df['cool_load'].values.reshape(-1, 1))


In [19]:
# Create sequences for training
sequence_length = 10
X, y = [], []
for i in range(len(df) - sequence_length):
    X.append(df['cool_load_normalized'].values[i:i+sequence_length])
    y.append(df['cool_load_normalized'].values[i+sequence_length])

X = np.array(X)
y = np.array(y)

In [20]:
nan_indices = np.isnan(y)
X = X[~nan_indices]
y = y[~nan_indices]

In [21]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [22]:
X_train

array([[0.05379856, 0.04980047, 0.04598174, ..., 0.02927571, 0.02633133,
        0.02348409],
       [0.43802592, 0.4169631 , 0.39724543, ..., 0.3150754 , 0.30132124,
        0.28835548],
       [0.69761012, 0.71326244, 0.72989747, ..., 0.81482132, 0.83135173,
        0.8478784 ],
       ...,
       [0.04232741, 0.03884123, 0.03550824, ..., 0.02072653, 0.01804744,
        0.01543934],
       [0.89622536, 0.91178427, 0.9266706 , ..., 0.98452703, 0.99143214,
        0.99641667],
       [0.99933863, 1.        , 0.99821768, ..., 0.94407909, 0.92180938,
        0.89465228]])

In [23]:
X_test

array([[0.97582465, 0.98452703, 0.99143214, 0.99641667, 0.99933863,
        1.        , 0.99821768, 0.9937712 , 0.9864364 , 0.97597411],
       [0.58407192, 0.59463509, 0.60403246, 0.61223415, 0.61921025,
        0.62527837, 0.63092053, 0.63665237, 0.64297458, 0.65038785],
       [0.9937712 , 0.9864364 , 0.97597411, 0.96198081, 0.94407909,
        0.92180938, 0.89465228, 0.86209589, 0.82307531, 0.77798287],
       [0.02633133, 0.02348409, 0.02072653, 0.01804744, 0.01543934,
        0.01292839, 0.01051086, 0.00818674, 0.00596724, 0.00384489],
       [0.22629172, 0.22830944, 0.23168727, 0.23675027, 0.24387583,
        0.25353849, 0.26594751, 0.28141301, 0.29921757, 0.31798616],
       [0.51668361, 0.53173808, 0.54609757, 0.55972843, 0.57243637,
        0.58407192, 0.59463509, 0.60403246, 0.61223415, 0.61921025],
       [0.04980047, 0.04598174, 0.04232741, 0.03884123, 0.03550824,
        0.03233219, 0.02927571, 0.02633133, 0.02348409, 0.02072653],
       [0.92180938, 0.89465228, 0.8620958

In [24]:
y_train

array([0.02072653, 0.27613329, 0.86424066, 0.77798287, 0.91178427,
       0.24387583, 0.05797226, 0.67046049, 0.57243637, 0.07374789,
       0.43802592, 0.34501995, 0.55972843, 0.01051086, 0.24349844,
       0.28141301, 0.01845098, 0.64297458, 0.68326931, 1.        ,
       0.43205121, 0.22158369, 0.79816013, 0.65038785, 0.02633133,
       0.22830944, 0.20762028, 0.10961484, 0.99821768, 0.20163809,
       0.61223415, 0.63665237, 0.97597411, 0.53173808, 0.03884123,
       0.98452703, 0.74698836, 0.83135173, 0.46759308, 0.23675027,
       0.23168727, 0.3150754 , 0.03233219, 0.35647242, 0.69761012,
       0.81482132, 0.54527927, 0.39724543, 0.02927571, 0.01543934,
       0.9937712 , 0.04598174, 0.00596724, 0.26594751, 0.72989747,
       0.19966521, 0.03550824, 0.89465228, 0.36137474, 0.58468845,
       0.54609757, 0.48457934, 0.9864364 , 0.41358154, 0.18469293,
       0.61921025, 0.19203521, 0.8478784 , 0.46059082, 0.99641667,
       0.31798616, 0.59463509, 0.99143214, 0.45006128, 0.97582

In [25]:
y_test

array([0.96198081, 0.65947509, 0.72817493, 0.00182343, 0.33717324,
       0.62527837, 0.01804744, 0.51208394, 0.253744  , 0.22466259,
       0.37569686, 0.29921757, 0.17954773, 0.92180938, 0.32961798,
       0.22471117, 0.50095655, 0.04232741, 0.9266706 , 0.88036753,
       0.94061533, 0.14763029, 0.00818674, 0.00384489, 0.02348409,
       0.48488947, 0.39476437])

In [26]:
# Reshape the data for CNN input (samples, time steps, features)
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))


In [27]:
# Build the CNN model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(sequence_length, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))  # Use 'linear' activation for regression

model.compile(optimizer='adam', loss='mean_squared_error')


In [28]:
# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), verbose=2)


Epoch 1/50
4/4 - 0s - loss: 0.2809 - val_loss: 0.1055 - 435ms/epoch - 109ms/step
Epoch 2/50
4/4 - 0s - loss: 0.0985 - val_loss: 0.0221 - 41ms/epoch - 10ms/step
Epoch 3/50
4/4 - 0s - loss: 0.0217 - val_loss: 0.0137 - 41ms/epoch - 10ms/step
Epoch 4/50
4/4 - 0s - loss: 0.0204 - val_loss: 0.0272 - 37ms/epoch - 9ms/step
Epoch 5/50
4/4 - 0s - loss: 0.0272 - val_loss: 0.0190 - 32ms/epoch - 8ms/step
Epoch 6/50
4/4 - 0s - loss: 0.0173 - val_loss: 0.0093 - 33ms/epoch - 8ms/step
Epoch 7/50
4/4 - 0s - loss: 0.0132 - val_loss: 0.0090 - 31ms/epoch - 8ms/step
Epoch 8/50
4/4 - 0s - loss: 0.0157 - val_loss: 0.0090 - 32ms/epoch - 8ms/step
Epoch 9/50
4/4 - 0s - loss: 0.0143 - val_loss: 0.0078 - 30ms/epoch - 8ms/step
Epoch 10/50
4/4 - 0s - loss: 0.0128 - val_loss: 0.0091 - 32ms/epoch - 8ms/step
Epoch 11/50
4/4 - 0s - loss: 0.0124 - val_loss: 0.0086 - 33ms/epoch - 8ms/step
Epoch 12/50
4/4 - 0s - loss: 0.0119 - val_loss: 0.0072 - 33ms/epoch - 8ms/step
Epoch 13/50
4/4 - 0s - loss: 0.0115 - val_loss: 0.0068 -

In [29]:
# Make predictions
predictions = model.predict(X_test)

1/1 [==============================] - 0s 69ms/step


In [35]:

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
rmse

0.0362203149495015